branches:
  only:
    - master
    - rust-0.9
    - rust-0.10
    - rust-mac

env:
  global:
    - secure: l/QiDLC5/4FiebGhIVjk3XrA6nUQV9xNZUb/a79UOOgUYWJhtg6TR8EOHQ+GvQcTUVn7QJIESIqOg9AcwcdoNY/iqgDiTIdnm+TlSnGD6gKGN4bswmEJqNUjxYFLt61cqfDuYSF7Iiwywm2Ux5iFt1Bbco9k8uMmqGets9zto84=

before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - yes | sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
  - yes | sudo apt-add-repository 'deb http://repos.codelite.org/wx3.0/ubuntu/ precise universe'
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly libclang-3.3-dev libwxgtk3.0-0-unofficial libwxgtk3.0-dev
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make doc

after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh >& /dev/null
