language: objective-c

branches:
  only:
    - master
    - rust-0.8
    - rust-0.9
    - rust-0.10
    - rust-mac

before_install:
  - brew update
install:
  - brew install rust wxmac
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
